"""Terraform wrapper — init, plan, apply, destroy, and chain generation."""

from __future__ import annotations

import json
import subprocess
import textwrap
from pathlib import Path
from typing import Any

from saboteur.utils.output import console, print_error, print_info, print_success

TERRAFORM_DIR = Path(__file__).resolve().parent.parent.parent / "terraform"
CHAIN_TF_FILENAME = "chain.tf"


def _sanitize_block_name(module_id: str) -> str:
    """Convert a module ID like 'WEB-SSRF' to a Terraform-safe name like 'web_ssrf'."""
    return module_id.lower().replace("-", "_")


class TerraformRunner:
    """Wraps Terraform CLI commands for scenario deployment."""

    def __init__(self, working_dir: Path | None = None) -> None:
        self.working_dir = working_dir or TERRAFORM_DIR

    def _run(self, args: list[str]) -> subprocess.CompletedProcess:
        cmd = ["terraform", *args]
        return subprocess.run(
            cmd,
            cwd=self.working_dir,
            capture_output=True,
            text=True,
        )

    def generate_chain_tf(self, chain: list[dict[str, Any]]) -> Path:
        """Generate chain.tf with a module block for each step in the attack chain.

        Terraform requires literal ``source`` paths in module blocks, so we
        cannot use ``for_each`` with dynamic sources.  Instead we generate one
        ``module`` block per chain step at deploy time.
        """
        blocks: list[str] = [
            "# Auto-generated by AZSaboteur — do not edit manually.",
            "# Re-generated on every `saboteur deploy`.\n",
        ]

        for step in chain:
            idx = step["step"]
            module_id = step["module_id"]
            source = f"./{step['module']}"
            block_name = f"step_{idx}_{_sanitize_block_name(module_id)}"

            block = textwrap.dedent(f"""\
                module "{block_name}" {{
                  source = "{source}"

                  scenario_id         = var.scenario_id
                  region              = var.region
                  resource_group_name = module.resource_group.name
                  lab_subnet_id       = module.networking.lab_subnet_id
                  resource_prefix     = var.chain[{idx}].config.resource_prefix
                  step_index          = {idx}
                  flag                = var.flags["{idx}"]
                  credentials         = var.credentials

                  depends_on = [module.kalibox]
                }}
            """)
            blocks.append(block)

        chain_tf = self.working_dir / CHAIN_TF_FILENAME
        chain_tf.write_text("\n".join(blocks))
        print_info(f"Generated {CHAIN_TF_FILENAME} with {len(chain)} module(s)")
        return chain_tf

    def clean_chain_tf(self) -> None:
        """Remove the generated chain.tf file."""
        chain_tf = self.working_dir / CHAIN_TF_FILENAME
        if chain_tf.exists():
            chain_tf.unlink()

    def init(self) -> bool:
        with console.status("Initializing Terraform...", spinner="dots"):
            result = self._run(["init", "-input=false", "-no-color"])
        if result.returncode == 0:
            print_success("Terraform initialized")
            return True
        print_error(f"Terraform init failed:\n{result.stderr}")
        return False

    def plan(self, var_file: Path | None = None) -> bool:
        args = ["plan", "-input=false", "-no-color", "-compact-warnings"]
        if var_file:
            args.append(f"-var-file={var_file}")
        with console.status("Planning infrastructure...", spinner="dots"):
            result = self._run(args)
        return result.returncode == 0

    def apply(self, var_file: Path | None = None, auto_approve: bool = True) -> bool:
        args = ["apply", "-input=false", "-no-color", "-compact-warnings"]
        if auto_approve:
            args.append("-auto-approve")
        if var_file:
            args.append(f"-var-file={var_file}")
        with console.status("Deploying infrastructure...", spinner="dots"):
            result = self._run(args)
        if result.returncode == 0:
            print_success("Infrastructure deployed")
            return True
        print_error(f"Terraform apply failed:\n{result.stderr}")
        return False

    def destroy(self, var_file: Path | None = None, auto_approve: bool = True) -> bool:
        args = ["destroy", "-input=false", "-no-color", "-compact-warnings"]
        if auto_approve:
            args.append("-auto-approve")
        if var_file:
            args.append(f"-var-file={var_file}")
        with console.status("Tearing down infrastructure...", spinner="dots"):
            result = self._run(args)
        if result.returncode == 0:
            self.clean_chain_tf()
            print_success("All resources destroyed")
            return True
        print_error(f"Terraform destroy failed:\n{result.stderr}")
        return False

    def output(self) -> dict[str, Any]:
        result = self._run(["output", "-json", "-no-color"])
        if result.returncode == 0:
            return json.loads(result.stdout)
        return {}

    def write_var_file(self, scenario_vars: dict[str, Any], filename: str = "scenario.auto.tfvars.json") -> Path:
        """Write scenario variables to a tfvars JSON file."""
        var_file = self.working_dir / filename
        with open(var_file, "w") as f:
            json.dump(scenario_vars, f, indent=2)
        return var_file
