"""Terraform wrapper — init, plan, apply, destroy, and chain generation."""

from __future__ import annotations

import json
import subprocess
import sys
import textwrap
from pathlib import Path
from typing import Any

from saboteur.utils.output import console, print_error, print_info, print_success, print_warning

TERRAFORM_DIR = Path(__file__).resolve().parent.parent.parent / "terraform"
CHAIN_TF_FILENAME = "chain.tf"


def _sanitize_block_name(module_id: str) -> str:
    """Convert a module ID like 'WEB-SSRF' to a Terraform-safe name like 'web_ssrf'."""
    return module_id.lower().replace("-", "_")


class TerraformRunner:
    """Wraps Terraform CLI commands for scenario deployment."""

    def __init__(
        self,
        working_dir: Path | None = None,
        verbose: bool = False,
        scenario_id: str | None = None,
    ) -> None:
        self.working_dir = working_dir or TERRAFORM_DIR
        self.verbose = verbose
        self.scenario_id = scenario_id

    def _run(self, args: list[str]) -> subprocess.CompletedProcess:
        cmd = ["terraform", *args]
        if self.verbose:
            # Stream stdout/stderr to the terminal in real-time
            result = subprocess.run(
                cmd,
                cwd=self.working_dir,
                stdout=sys.stdout,
                stderr=sys.stderr,
                text=True,
            )
            # stdout/stderr were streamed, not captured
            return subprocess.CompletedProcess(
                args=result.args,
                returncode=result.returncode,
                stdout="",
                stderr="",
            )
        return subprocess.run(
            cmd,
            cwd=self.working_dir,
            capture_output=True,
            text=True,
        )

    def generate_chain_tf(self, chain: list[dict[str, Any]]) -> Path:
        """Generate chain.tf with a module block for each step in the attack chain.

        Terraform requires literal ``source`` paths in module blocks, so we
        cannot use ``for_each`` with dynamic sources.  Instead we generate one
        ``module`` block per chain step at deploy time.
        """
        blocks: list[str] = [
            "# Auto-generated by AZSaboteur — do not edit manually.",
            "# Re-generated on every `saboteur deploy`.\n",
        ]

        for step in chain:
            idx = step["step"]
            module_id = step["module_id"]
            source = f"./{step['module']}"
            block_name = f"step_{idx}_{_sanitize_block_name(module_id)}"

            block = textwrap.dedent(f"""\
                module "{block_name}" {{
                  source = "{source}"

                  scenario_id         = var.scenario_id
                  region              = var.region
                  resource_group_name = module.resource_group.name
                  lab_subnet_id       = module.networking.lab_subnet_id
                  resource_prefix     = var.chain[{idx}].config.resource_prefix
                  step_index          = {idx}
                  flag                = var.flags["{idx}"]
                  credentials         = var.credentials

                  depends_on = [module.kalibox]
                }}
            """)
            blocks.append(block)

        chain_tf = self.working_dir / CHAIN_TF_FILENAME
        chain_tf.write_text("\n".join(blocks))
        print_info(f"Generated {CHAIN_TF_FILENAME} with {len(chain)} module(s)")
        return chain_tf

    def clean_chain_tf(self) -> None:
        """Remove the generated chain.tf file."""
        chain_tf = self.working_dir / CHAIN_TF_FILENAME
        if chain_tf.exists():
            chain_tf.unlink()

    def state_list(self) -> list[str]:
        """List all resources in the current workspace's Terraform state."""
        result = self._run(["state", "list"])
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip().splitlines()
        return []

    def state_rm(self, address: str) -> bool:
        """Remove a resource from the Terraform state (does not delete the real resource)."""
        result = self._run(["state", "rm", address])
        return result.returncode == 0

    def _select_workspace(self) -> bool:
        """Select (or create) the Terraform workspace for this scenario."""
        if not self.scenario_id:
            return True
        result = self._run(["workspace", "select", "-or-create", self.scenario_id])
        if result.returncode == 0:
            return True
        print_error(f"Failed to select workspace '{self.scenario_id}':\n{result.stderr}")
        return False

    def _delete_workspace(self) -> bool:
        """Delete the scenario workspace after destroy, switching back to default."""
        if not self.scenario_id:
            return True
        self._run(["workspace", "select", "default"])
        result = self._run(["workspace", "delete", self.scenario_id])
        if result.returncode != 0:
            print_warning(f"Could not delete workspace '{self.scenario_id}' (may already be removed)")
        return True

    def init(self) -> bool:
        if self.verbose:
            print_info("Running: terraform init")
            result = self._run(["init", "-input=false", "-no-color", "-upgrade"])
        else:
            with console.status("[bold blue]Initializing Terraform...", spinner="dots", spinner_style="blue"):
                result = self._run(["init", "-input=false", "-no-color", "-upgrade"])
        if result.returncode != 0:
            print_error(f"Terraform init failed:\n{result.stderr}")
            return False

        if not self._select_workspace():
            return False

        print_success("Terraform initialized")
        return True

    def plan(self, var_file: Path | None = None) -> bool:
        args = ["plan", "-input=false", "-no-color", "-compact-warnings"]
        if var_file:
            args.append(f"-var-file={var_file}")
        with console.status("[bold blue]Planning infrastructure...", spinner="dots", spinner_style="blue"):
            result = self._run(args)
        return result.returncode == 0

    def apply(self, var_file: Path | None = None) -> bool:
        args = ["apply", "-auto-approve", "-input=false", "-no-color", "-compact-warnings"]
        if var_file:
            args.append(f"-var-file={var_file}")
        if self.verbose:
            print_info("Running: terraform apply")
            result = self._run(args)
        else:
            with console.status("[bold blue]Deploying infrastructure...", spinner="dots", spinner_style="blue"):
                result = self._run(args)
        if result.returncode == 0:
            print_success("Infrastructure deployed")
            return True
        print_error(f"Terraform apply failed:\n{result.stderr}")
        return False

    def destroy(self, var_file: Path | None = None) -> bool:
        args = ["destroy", "-auto-approve", "-input=false", "-no-color", "-compact-warnings"]
        if var_file:
            args.append(f"-var-file={var_file}")
        if self.verbose:
            print_info("Running: terraform destroy")
            result = self._run(args)
        else:
            with console.status("[bold blue]Tearing down infrastructure...", spinner="dots", spinner_style="blue"):
                result = self._run(args)
        if result.returncode == 0:
            self.clean_chain_tf()
            self._delete_workspace()
            print_success("All resources destroyed")
            return True
        print_error(f"Terraform destroy failed:\n{result.stderr}")
        return False

    def output(self) -> dict[str, Any]:
        # Always capture stdout for output parsing, even in verbose mode
        result = subprocess.run(
            ["terraform", "output", "-json", "-no-color"],
            cwd=self.working_dir,
            capture_output=True,
            text=True,
        )
        if result.returncode == 0 and result.stdout.strip():
            return json.loads(result.stdout)
        return {}

    def write_var_file(self, scenario_vars: dict[str, Any], filename: str = "scenario.auto.tfvars.json") -> Path:
        """Write scenario variables to a tfvars JSON file."""
        var_file = self.working_dir / filename
        with open(var_file, "w") as f:
            json.dump(scenario_vars, f, indent=2)
        return var_file
