# Exposed management port — VM with SSH directly accessible from the lab subnet.
# The player discovers credentials via an internal deployment page (port 8080)
# that leaks SSH credentials in HTML source, then logs in via SSH.

locals {
  admin_user = var.credentials["step_${var.step_index}_username"]
  admin_pass = var.credentials["step_${var.step_index}_password"]
}

resource "azurerm_network_interface" "this" {
  name                = "nic-${var.resource_prefix}"
  location            = var.region
  resource_group_name = var.resource_group_name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = var.lab_subnet_id
    private_ip_address_allocation = "Dynamic"
  }

  tags = {
    project  = "azsaboteur"
    scenario = var.scenario_id
    step     = var.step_index
  }
}

# NSG allowing SSH and HTTP from the lab subnet
resource "azurerm_network_security_group" "this" {
  name                = "nsg-${var.resource_prefix}"
  location            = var.region
  resource_group_name = var.resource_group_name

  security_rule {
    name                       = "AllowSSH"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "22"
    source_address_prefix      = "10.13.37.0/24"
    destination_address_prefix = "*"
  }

  security_rule {
    name                       = "AllowHTTP"
    priority                   = 120
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "8080"
    source_address_prefix      = "10.13.37.0/24"
    destination_address_prefix = "*"
  }

  tags = {
    project  = "azsaboteur"
    scenario = var.scenario_id
    step     = var.step_index
  }
}

resource "azurerm_network_interface_security_group_association" "this" {
  network_interface_id      = azurerm_network_interface.this.id
  network_security_group_id = azurerm_network_security_group.this.id
}

resource "azurerm_linux_virtual_machine" "this" {
  name                            = "${var.resource_prefix}-vm"
  location                        = var.region
  resource_group_name             = var.resource_group_name
  size                            = "Standard_B2ls_v2"
  admin_username                  = local.admin_user
  admin_password                  = local.admin_pass
  disable_password_authentication = false
  network_interface_ids           = [azurerm_network_interface.this.id]

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts-gen2"
    version   = "latest"
  }

  custom_data = base64encode(<<-CLOUD
    #!/bin/bash
    set -e
    mkdir -p /opt/azsaboteur
    echo '${var.flag}' > /opt/azsaboteur/flag.txt
    chmod 600 /opt/azsaboteur/flag.txt

    # SSH banner leaks the username
    printf '%s\n' \
      '************************************************************' \
      '  CONTOSO LABS - Deployment Gateway' \
      '  Authorized access only. All sessions are monitored.' \
      '' \
      '  System account : ${local.admin_user}' \
      '  Support contact: ${local.admin_user}@contoso-labs.com' \
      '  Managed by     : ops-team@contoso-labs.com' \
      '************************************************************' > /etc/ssh/banner
    sed -i 's/^#\?Banner.*/Banner \/etc\/ssh\/banner/' /etc/ssh/sshd_config
    systemctl restart ssh || systemctl restart sshd

    # Internal deployment page on port 8080 — leaks credentials in HTML source
    mkdir -p /opt/azsaboteur/deploy-portal
    cat > /opt/azsaboteur/deploy-portal/index.html << 'HTMLEOF'
<!DOCTYPE html>
<html>
<head><title>Contoso Labs — Deployment Portal</title></head>
<body>
  <h1>Contoso Labs Deployment Portal</h1>
  <p>Status: <span style="color:green">&#x2713; All systems operational</span></p>

  <h2>Quick Links</h2>
  <ul>
    <li><a href="#">Azure Portal</a></li>
    <li><a href="#">Monitoring Dashboard</a></li>
    <li><a href="#">Runbook Library</a></li>
  </ul>

  <p><em>Managed by ops-team@contoso-labs.com</em></p>

  <!--
    DEPLOYMENT CREDENTIALS (auto-generated by Terraform)
    TODO: move these to Key Vault before production launch!

    SSH_HOST: ${azurerm_network_interface.this.private_ip_address}
    SSH_USER: ${local.admin_user}
    SSH_PASS: ${local.admin_pass}
  -->
</body>
</html>
HTMLEOF

    # Serve the deployment page
    cat > /etc/systemd/system/deploy-portal.service << 'SVCEOF'
[Unit]
Description=Contoso Labs Deployment Portal
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/azsaboteur/deploy-portal
ExecStart=/usr/bin/python3 -m http.server 8080
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
SVCEOF
    systemctl daemon-reload
    systemctl enable deploy-portal
    systemctl start deploy-portal
  CLOUD
  )

  tags = {
    project  = "azsaboteur"
    scenario = var.scenario_id
    step     = var.step_index
    role     = "mgmt-exposed"
  }
}

output "private_ip" {
  description = "Private IP of the VM"
  value       = azurerm_network_interface.this.private_ip_address
}

output "vm_id" {
  description = "VM resource ID"
  value       = azurerm_linux_virtual_machine.this.id
}
