# Open NSG — intentionally misconfigured to allow all inbound traffic.
# The player discovers internal services that should not be exposed.
# Port 8080 runs a deployment portal with credentials leaked in HTML source.

locals {
  admin_user = var.credentials["step_${var.step_index}_username"]
  admin_pass = var.credentials["step_${var.step_index}_password"]
}

resource "azurerm_network_security_group" "this" {
  name                = "nsg-${var.resource_prefix}"
  location            = var.region
  resource_group_name = var.resource_group_name

  # Intentionally permissive: allow all inbound
  security_rule {
    name                       = "AllowAllInbound"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }

  tags = {
    project  = "azsaboteur"
    scenario = var.scenario_id
    step     = var.step_index
    role     = "nsg-open"
  }
}

# A VM behind the open NSG that hosts services with the flag
resource "azurerm_network_interface" "this" {
  name                = "nic-${var.resource_prefix}"
  location            = var.region
  resource_group_name = var.resource_group_name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = var.lab_subnet_id
    private_ip_address_allocation = "Dynamic"
  }

  tags = {
    project  = "azsaboteur"
    scenario = var.scenario_id
    step     = var.step_index
  }
}

resource "azurerm_network_interface_security_group_association" "this" {
  network_interface_id      = azurerm_network_interface.this.id
  network_security_group_id = azurerm_network_security_group.this.id
}

resource "azurerm_linux_virtual_machine" "this" {
  name                            = "${var.resource_prefix}-vm"
  location                        = var.region
  resource_group_name             = var.resource_group_name
  size                            = "Standard_B2ls_v2"
  admin_username                  = local.admin_user
  admin_password                  = local.admin_pass
  disable_password_authentication = false
  network_interface_ids           = [azurerm_network_interface.this.id]

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts-gen2"
    version   = "latest"
  }

  custom_data = base64encode(<<-CLOUD
    #!/bin/bash
    set -e
    mkdir -p /opt/azsaboteur
    echo '${var.flag}' > /opt/azsaboteur/flag.txt
    chmod 600 /opt/azsaboteur/flag.txt

    # Internal deployment page on port 8080 — leaks credentials in HTML source
    mkdir -p /opt/azsaboteur/deploy-portal
    cat > /opt/azsaboteur/deploy-portal/index.html << 'HTMLEOF'
<!DOCTYPE html>
<html>
<head><title>Internal Dashboard — AZ Corp</title></head>
<body>
  <h1>AZ Corp Internal Dashboard</h1>
  <p>Welcome to the internal management console.</p>
  <p>Authorised personnel only. All access is logged.</p>
  <div id="status">
    <h2>Service Status</h2>
    <ul>
      <li>API Gateway — <span style="color:green">Online</span></li>
      <li>Identity Provider — <span style="color:green">Online</span></li>
      <li>Key Vault — <span style="color:orange">Degraded</span></li>
    </ul>
  </div>

  <!--
    DEPLOYMENT CREDENTIALS (auto-generated by provisioning pipeline)
    TODO: remove hardcoded creds before next security audit!

    SSH_HOST: ${azurerm_network_interface.this.private_ip_address}
    SSH_USER: ${local.admin_user}
    SSH_PASS: ${local.admin_pass}
  -->

  <p><em>&copy; AZ Corp Internal Systems</em></p>
</body>
</html>
HTMLEOF

    # Serve the deployment page
    cat > /etc/systemd/system/deploy-portal.service << 'SVCEOF'
[Unit]
Description=AZ Corp Internal Dashboard
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/azsaboteur/deploy-portal
ExecStart=/usr/bin/python3 -m http.server 8080
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
SVCEOF
    systemctl daemon-reload
    systemctl enable deploy-portal
    systemctl start deploy-portal
  CLOUD
  )

  tags = {
    project  = "azsaboteur"
    scenario = var.scenario_id
    step     = var.step_index
    role     = "nsg-open"
  }
}

output "nsg_id" {
  description = "NSG resource ID"
  value       = azurerm_network_security_group.this.id
}

output "private_ip" {
  description = "Private IP of the VM behind the open NSG"
  value       = azurerm_network_interface.this.private_ip_address
}
